swagger: "2.0"

info:
  version: 1.0.0
  title: Simple API
  description: A simple API to learn how to write OpenAPI Specification

schemes:
  - http
host: localhost:8080
basePath: /v1/api

produces:
  - application/json

paths:
  /persons:
    $ref: 'paths/persons.yaml'
  /persons/{username}:
    $ref: 'paths/persons-{username}.yaml'
