swagger: "2.0"

info:
  version: 1.0.0
  title: Simple API
  description: A simple API to learn how to write OpenAPI Specification

schemes:
  - http
host: localhost:8080
basePath: /v1/api

paths:
  /persons:
    get:
      summary: Gets some persons
      description: Returns a list containing all persons.
      parameters:
        - name: pageSize
          in: query
          description: Number of persons returned
          required: true
          type: integer
        - name: pageNumber
          in: query
          description: Page Number
          required: true
          type: integer
      responses:
        200:
          description: A list of person
          schema:
            type: array
            items:
              required:
                - username
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                username:
                  type: string
    post:
      summary: create a person
      description: Adds a new person to the persons list.
      parameters:
        - name: person
          in: body
          description: The person to create.
          schema:
            required:
              - username
            properties:
              firstName:
                type: string
              lastName:
                type: string
              username:
                type: string
      responses:
        200:
          description: Person successfully created.
        400:
          description: Person couldn't have been created.                                
  /persons/{username}:
    get:
      summary: Gets a person
      description: Returns a single person for its username
      parameters:
        - name: username
          in: path
          required: true
          description: the person's username
          type: string
      responses:
        200:
          description: A person
          schema:
            required:
              - username
            properties:
              firstName:
                type: string
              lastName:
                type: string
              username:
                type: string
        404:
          description: the person does not exist
