/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hwen' at '1/19/16 10:32 AM' with Gradle 2.2
 *
 * @author hwen, @date 1/19/16 10:32 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
