/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hwen' at '9/24/15 5:50 PM' with Gradle 2.2
 *
 * @author hwen, @date 9/24/15 5:50 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
