/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hwen' at '10/2/15 10:50 AM' with Gradle 2.2
 *
 * @author hwen, @date 10/2/15 10:50 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
