kind: Service
apiVersion: v1
metadata:
  name: spring-cloud-config-server
  labels:
    app: spring-cloud-config-server
spec:
  selector:
    app: spring-cloud-config-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: NodePort