wordpress:
  image: daocloud.io/daocloud/dao-wordpress:latest
  links:
    - db:mysql
  ports:
    - "80"
  restart: always
db:
  image: mysql
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=
  restart: always
