/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'wenhao' at '9/16/15 10:30 PM' with Gradle 2.6
 *
 * @author wenhao, @date 9/16/15 10:30 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
