/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hwen' at '8/12/15 1:27 PM' with Gradle 2.2
 *
 * @author hwen, @date 8/12/15 1:27 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
