kind: Service
apiVersion: v1
metadata:
  name: orange-collector
  labels:
    app: orange-collector
spec:
  selector:
    app: orange-collector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080