global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - 'localhost:9093'

rule_files:
   # - "./rules/load_rules.yml"      

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:7070'] 
  
remote_read:
  - url: "http://127.0.0.1:8086/api/v1/prom/read?db=prometheus"

# prometheus --config.file=./prometheus-read.yml --web.listen-address=:7070 --storage.tsdb.path=./data-read   