global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.126.com:25'
  smtp_from: 'wenhao@126.com'
  smtp_auth_username: 'wenhao@126.com'
  smtp_auth_password: '1qaz!QAZ'

templates:
  - 'template/*.tmpl'  

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'wenhao@126.com'
    html: '{{ template "email.html" . }}'
    headers: 
      Subject: '[WARN] 报警邮件'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
