/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hwen' at '12/9/15 2:49 PM' with Gradle 2.2
 *
 * @author hwen, @date 12/9/15 2:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
