Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "shell", path: "./provision/provision.sh"
  config.vm.box_check_update = false

  forward_port = ->(guest, host = guest) do
    config.vm.network :forwarded_port,
      guest: guest,
      host: host,
      auto_correct: true
  end

  forward_port[80, 9999]
  forward_port[3306]

  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "./salient", "/var/www/html/wp-content/themes/salient"
end
