/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'wenhao' at '17-10-31 下午7:34' with Gradle 3.2.1
 *
 * @author wenhao, @date 17-10-31 下午7:34
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
