server:
  port: 8080

spring:
  cloud:
    routes:
      - id: service-provider
        predicates:
        - Path=/service-provider/**
        uri: "http://spring-cloud-service-provider.microservice:80"