server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wenhao/spring-config-server.git
          username: wenhao@126.com
          password: 1qaz!QAZ
          clone-on-start: true
  security:
    user:
      name: admin
      password: password