apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-order-service
  labels:
    app: spring-cloud-order-service
spec:
  selector:
    matchLabels:
      app: spring-cloud-order-service
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-cloud-order-service
    spec:
      containers:
        - name: order-service
          image: wenhao/spring-cloud-order-service:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: CONFIG_SERVER_URL
              value: "http://spring-cloud-config-server.microservice:80"
            - name: EUREKA_URL
              value: "http://spring-cloud-eureka-server.microservice:80/eureka"