kind: Service
apiVersion: v1
metadata:
  name: spring-cloud-service-provider
  labels:
    app: spring-cloud-service-provider
spec:
  selector:
    app: spring-cloud-service-provider
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
