/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'wenhao' at '11/7/15 10:58 PM' with Gradle 2.6
 *
 * @author wenhao, @date 11/7/15 10:58 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
