apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-product-service
  labels:
    app: spring-cloud-product-service
spec:
  selector:
    matchLabels:
      app: spring-cloud-product-service
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-cloud-product-service
    spec:
      containers:
        - name: product-service
          image: wenhao/spring-cloud-product-service:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_URL
              value: "http://spring-cloud-eureka-server:80/eureka/"
