kind: Service
apiVersion: v1
metadata:
  name: spring-cloud-eureka-client
  labels:
    app: spring-cloud-eureka-client
spec:
  selector:
    app: spring-cloud-eureka-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
