spring:
  messages:
    basename: ValidationMessages
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

endpoints:
  cors:
    allow-credentials: true
    allowed-headers: *
    allowed-methods: *
    allowed-origins: *
    max-age: 3600
